### PR TITLE
Two drugs

### PR DESCRIPTION
**Pull request by Farnazmdi**

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Please tag me when you're done making changes.

**Comment by Farnazmdi** [comment]
Sorry, will do.

**Comment by Farnazmdi** [comment]
@aarmey Sorry, I had some problems with resolving conflicts for `Manifest.toml`. This is finished now.

There are 3 functions in the new file `DrugPairs.jl` -- I really tried to keep it succinct. The functions are called in the notebook `pairsDrugs.ipynb`. Each case has its own `getODEparams()`, there was no easy way of defining a common function, so I had to write for each case.

**Review by aarmey — APPROVED** [review]
Removed some code duplication. This is ready to merge.

Look at the BlackBoxOptim documentation about multi-threading. You can speed up fitting by ~20X with that.

**Comment by Farnazmdi** [comment]
Thank you so much, will do.
I'll merge this and add the multi-threading in another branch.

**Pull request merged**
