### PR TITLE
Std format

### PR DESCRIPTION
**Pull request by Farnazmdi**
There are many things wrong with this branch I guess, I made the PR to see where the conflicts are.

### CODE REVIEW

**Comment by Farnazmdi** [comment]
The conflicts are resolved, but the tests keep failing, and the checks take like 13-15 minutes to finish.

**Comment by aarmey** [comment]
Indeed, Travis is slow. You'll want to run them on your account locally. I'll take a look right now.

**Comment by Farnazmdi** [comment]
Thank you, will run them locally from now.

**Comment by aarmey** [comment]
Here was what was missing and why `get_data` was missing: https://github.com/meyer-lab/DrugResponseModel.jl/pull/11/commits/51c26dcc7411387df11abae5b3766028b7167113

Now `remove_peaks` is undefined. I don't see that anywhere in this code?

**Comment by Farnazmdi** [comment]
Oh I will add it right away, I kept moving functions around, missed this one.

**Comment by Farnazmdi** [comment]
@aarmey I couldn't run the tests locally, could you please tell me how you do it?
I tried this:
image

**Comment by aarmey** [comment]
Drop by my office.

**Comment by aarmey** [comment]
FYI—I don't think you want to run actual fitting within your tests. You just want to check that your code works. For example, you could run the black box fitting but limit it to 2-3 iterations.

**Comment by Farnazmdi** [comment]
Finally! I added another argument to control the number of iterations and updated notebooks a bit.
I will try some more `alg()` for DDE solver to see if I can get a better fit. Could I merge now?

**Comment by aarmey** [comment]
Yes, please merge. The DDE solver shouldn't affect your fit but might speed up solving...

**Pull request merged**
