### PR TITLE
Compare

### PR DESCRIPTION
**Pull request by Farnazmdi**

### CODE REVIEW

**Comment by Farnazmdi** [comment]
#270

**Comment by Farnazmdi** [comment]
I will work on it after the qual, if that's alright. I have to correct some part so that the time-series simulations in the temporal combination work.

**Comment by aarmey** [comment]
Sounds good.

**Comment by Farnazmdi** [comment]
This PR does  the following:
for any set of (drugA_conc_x, drugB_conc_y) finds the different simulation results in terms of cell number for the two different orders of treatment with drugA and drugB, and outputs a heatmap showing the difference, and plots the time-series of the one with the highest difference between the two treatment orders

**Comment by Farnazmdi** [comment]
The results are in `temporal_combin.pdf`.
I will take care of the rest in another PR. 
Should I merge this @aarmey ?

**Comment by Farnazmdi** [comment]
Since you've approved it before, I guess it is fine to merge.

**Pull request merged**
