### PR TITLE
plot temporal combination

### PR DESCRIPTION
**Pull request by Farnazmdi**

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Oh, I'm gonna need to unify the time-axis maximum.

**Comment by Farnazmdi** [comment]
Should I send all of the combinations to Drs. Gross and Heiser? Or this is enough? I thought I could ask them to see which combinations they intend to see, and then I can simulate provide to them.

**Comment by Farnazmdi** [comment]
image

**Comment by aarmey** [comment]
Are any drugs/concentrations really different in the final cell # during the A->B direction compared to the B->A direction?

**Comment by Farnazmdi** [comment]
A little yes, I will send you a file I have prepared that has all the 6 combinations, all in an intermediate concentration.

**Pull request closed without merging**
