### PR TITLE
Figs

### PR DESCRIPTION
**Pull request by Farnazmdi**
Figure1 w/o the cartoon:
image

FigureS1 w/o the cartoon:
image

Please let me know if anything needs to be changed for now @aarmey.
Thank you.

### CODE REVIEW

**Comment by Farnazmdi** [comment]
With few adjustments:
image

**Comment by aarmey** [comment]
Shouldn't the other two drugs be in the supplement?

**Comment by aarmey** [comment]
Also, check that your labels have consistent capitalization.

**Review by aarmey — CHANGES_REQUESTED** [review]
You have empty files here. Are those needed?

Also, please don't commit the svg's.

**Comment by Farnazmdi** [comment]
Should I put the other 3 drugs in the same figure as the simple_ODE? Or they could be separate? I mean space-wise, do we have enough space to have them as a separate figure?
The empty subfigures are for the cartoons of the model.
Of  course, I will remove the svg files,

**Comment by aarmey** [comment]
You have space in the supplement. The simple ODE model should come after the full model for the other drugs.

**Comment by Farnazmdi** [comment]
I made figureS1 as the rest of the model-data comparison:
image
The figure for simple ODE is now figure S2.
I fixed the capitalization and removed the svg files.
Could I merge this?

**Comment by aarmey** [comment]
You can't just split these into more figures. Most journals require that there be at most one supplementary figure per main figure.

**Review by aarmey — CHANGES_REQUESTED** [review]
What are the .jld files?

**Comment by Farnazmdi** [comment]
They are the G1 and G2 cell numbers for the simple ODE model (the reference model) brcause I had to write a different ODEjac() and predict() so I decided to just save the cell numbers and load them for plotting the figureS2.

**Comment by aarmey** [comment]
Ok, we can merge this after the figure changes, but I would strongly advise against doing this. If those numbers need to be changed, then you will have to recreate the model from scratch. It also hides the relationship between the results and underlying code.

**Comment by Farnazmdi** [comment]
Oh I thought when you said the figure for simple model should come after the other one, it means as another figure.
I will put them together.

**Comment by Farnazmdi** [comment]
I modified the figures from this last commit in Affinity designer, and this is the result. 
image

image

Please let me know if you want anything changed. Otherwise, I will send them to you in Slack.

**Comment by aarmey** [comment]
Ok, this can be merged. I don't need the figure in Slack. You can start on the combination figure.

**Pull request merged**
