### PR TITLE
plot time series for IC50 conc of drugs

### PR DESCRIPTION
**Pull request by Farnazmdi**

### CODE REVIEW

**Comment by Farnazmdi** [comment]
image
This is what I have for drugs at their IC50.

**Comment by Farnazmdi** [comment]
Please look at it as a 2 row and 3 columns. Each plot actually is 4 sub-plots. When providing to Heiser lab, I will draw a line to separate them.
Do these results make sense to you?

**Comment by aarmey** [comment]
These make sense to me.

**Comment by Farnazmdi** [comment]
I thought I add the difference of Bliss combination in another branch, but since you haven't reviewed this, I will add it in this branch, if you agree.

**Pull request merged**
