### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by aarmey**
This sets up testing through Travis-ci. I'm seeing an error `LoadError: UndefVarError: get_data not defined`

### CODE REVIEW

**Comment by aarmey** [comment]
You can run the tests by loading Julia in the home folder, then `using Pkg`, `]`, `activate .`, `test`.

**Comment by aarmey** [comment]
This also pins all the package versions.

**Comment by Farnazmdi** [comment]
I have reverted two last commits to the master, could that be the reason the tests failed?
I still have that problem, I reverted to start over, I'll try to get it done by tonight

**Comment by aarmey** [comment]
This is on a separate branch, so I don't think so. Look at the bottom of the output from Travis: https://travis-ci.com/meyer-lab/one_state_model/builds/123444158

**Pull request merged**
